/* Theme engine — 11 styles × light/dark. Every visual decision is a CSS variable;
   each theme also picks a layout system and its own voice (strings). */

const base = {
  "--font-body": "'Plus Jakarta Sans', system-ui, sans-serif",
  "--font-display": "'Bricolage Grotesque', system-ui, sans-serif",
  "--font-label": "'Spline Sans Mono', monospace",
  "--lbl-transform": "uppercase",
  "--lbl-spacing": "2px",
  "--radius-card": "16px",
  "--radius-btn": "13px",
  "--bw": "1px",
  "--shadow-card": "none",
  "--shadow-btn": "none",
  "--bg-image": "none",
  "--glass": "0",
};

export const THEMES = {
  studio: {
    name: "Studio", hint: "Clean and quiet", layout: "list",
    strings: { pending: "On the desk", working: "In motion", recent: "Recent",
      directive: "Give a directive — it gets routed, deliberated, and lands back here…",
      send: "Send directive", daily: "Run daily ideas" },
    light: { ...base,
      "--bg": "#F7F6F3", "--panel": "#FFFFFF", "--line": "#E5E2DA", "--line-strong": "#C9C5BA",
      "--text": "#3A3831", "--bright": "#171512", "--dim": "#8A857B", "--label": "#8A857B",
      "--accent": "#FF6B4A", "--on-accent": "#2A0F06", "--danger": "#C0392B", "--ok": "#2E7D4F" },
    dark: { ...base,
      "--bg": "#141311", "--panel": "#1E1D1A", "--line": "#2E2C27", "--line-strong": "#4A4740",
      "--text": "#C9C5BA", "--bright": "#F1EFE9", "--dim": "#7E7A70", "--label": "#9A958A",
      "--accent": "#FF6B4A", "--on-accent": "#2A0F06", "--danger": "#E06050", "--ok": "#5FBF87" },
  },

  glass: {
    name: "Glass", hint: "Frosted command center", layout: "stack",
    strings: { pending: "Needs you", working: "In flight", recent: "History",
      directive: "Direct the company…", send: "Send", daily: "Daily cycle" },
    light: { ...base,
      "--bg": "#D9D4F5",
      "--bg-image": "linear-gradient(135deg,#C9C2F2 0%,#F3C4D8 55%,#FFD9BC 100%)",
      "--panel": "rgba(255,255,255,0.55)", "--line": "rgba(255,255,255,0.75)", "--line-strong": "rgba(255,255,255,0.95)",
      "--text": "#3A3355", "--bright": "#201A38", "--dim": "#6E668E", "--label": "#5E5680",
      "--accent": "#FF6B4A", "--on-accent": "#2A0F06", "--danger": "#C22F4B", "--ok": "#1F7A55",
      "--radius-card": "18px", "--radius-btn": "99px", "--glass": "1",
      "--shadow-card": "0 8px 24px rgba(60,50,120,0.14)" },
    dark: { ...base,
      "--bg": "#12101F",
      "--bg-image": "linear-gradient(135deg,#171430 0%,#2A1533 55%,#3A1E2A 100%)",
      "--panel": "rgba(255,255,255,0.08)", "--line": "rgba(255,255,255,0.16)", "--line-strong": "rgba(255,255,255,0.34)",
      "--text": "#CEC9E6", "--bright": "#F4F2FC", "--dim": "#847EA6", "--label": "#9C95C2",
      "--accent": "#FF7A5C", "--on-accent": "#2A0F06", "--danger": "#F0637E", "--ok": "#5ED6A0",
      "--radius-card": "18px", "--radius-btn": "99px", "--glass": "1",
      "--shadow-card": "0 8px 24px rgba(0,0,0,0.35)" },
  },

  editorial: {
    name: "Editorial", hint: "Big type, magazine energy", layout: "ledger",
    strings: { pending: "The docket", working: "With the team", recent: "The record",
      directive: "Dictate a directive to the company…", send: "Issue directive", daily: "Morning ideas" },
    light: { ...base,
      "--bg": "#FFFDF8", "--panel": "#FFFDF8", "--line": "#E7E2D6", "--line-strong": "#171512",
      "--text": "#33302A", "--bright": "#171512", "--dim": "#8A857B", "--label": "#C0392B",
      "--accent": "#C0392B", "--on-accent": "#FFF6F2", "--danger": "#C0392B", "--ok": "#2E6B47",
      "--font-display": "'Newsreader', Georgia, serif",
      "--font-label": "'Instrument Sans', sans-serif", "--lbl-spacing": "2.5px",
      "--radius-card": "0px", "--radius-btn": "0px" },
    dark: { ...base,
      "--bg": "#191713", "--panel": "#191713", "--line": "#33302A", "--line-strong": "#F1EDE2",
      "--text": "#CFC9BB", "--bright": "#F5F1E6", "--dim": "#847E71", "--label": "#E88070",
      "--accent": "#E8654F", "--on-accent": "#2A0F06", "--danger": "#E8654F", "--ok": "#6FBF93",
      "--font-display": "'Newsreader', Georgia, serif",
      "--font-label": "'Instrument Sans', sans-serif", "--lbl-spacing": "2.5px",
      "--radius-card": "0px", "--radius-btn": "0px" },
  },

  brutal: {
    name: "Brutal", hint: "Loud borders, rubber stamps", layout: "stamps",
    strings: { pending: "Needs your ink", working: "Cooking", recent: "Done + dusted",
      directive: "Bark an order at the company…", send: "Send it", daily: "Wake the team" },
    light: { ...base,
      "--bg": "#FDF6EC", "--panel": "#FFFFFF", "--line": "#111111", "--line-strong": "#111111",
      "--text": "#26241F", "--bright": "#111111", "--dim": "#6B675C", "--label": "#111111",
      "--accent": "#FFD23F", "--on-accent": "#111111", "--danger": "#FF4040", "--ok": "#B5E61D",
      "--font-display": "'Archivo', 'Instrument Sans', sans-serif",
      "--font-label": "'Archivo', sans-serif", "--lbl-spacing": "1px",
      "--radius-card": "0px", "--radius-btn": "0px", "--bw": "2.5px",
      "--shadow-card": "5px 5px 0 #111111", "--shadow-btn": "3px 3px 0 #111111" },
    dark: { ...base,
      "--bg": "#161616", "--panel": "#1F1F1F", "--line": "#F2EFE6", "--line-strong": "#F2EFE6",
      "--text": "#D9D5C9", "--bright": "#F7F4EA", "--dim": "#8F8B7F", "--label": "#F2EFE6",
      "--accent": "#FFD23F", "--on-accent": "#111111", "--danger": "#FF5A5A", "--ok": "#B5E61D",
      "--font-display": "'Archivo', 'Instrument Sans', sans-serif",
      "--font-label": "'Archivo', sans-serif", "--lbl-spacing": "1px",
      "--radius-card": "0px", "--radius-btn": "0px", "--bw": "2.5px",
      "--shadow-card": "5px 5px 0 #F2EFE6", "--shadow-btn": "3px 3px 0 #F2EFE6" },
  },

  dossier: {
    name: "Dossier", hint: "Case files and stamps", layout: "files",
    strings: { pending: "Open case files", working: "Under investigation", recent: "Archived",
      directive: "Open a new case…", send: "File it", daily: "Morning briefing" },
    light: { ...base,
      "--bg": "#E8DDC8", "--panel": "#F5EFDF", "--line": "#B09A6E", "--line-strong": "#7A6A4A",
      "--text": "#4A4233", "--bright": "#2E2818", "--dim": "#8A7C60", "--label": "#7A6A4A",
      "--accent": "#9A2B1E", "--on-accent": "#F8EFE6", "--danger": "#9A2B1E", "--ok": "#4A6B3A",
      "--font-display": "'Spline Sans Mono', monospace",
      "--radius-card": "3px", "--radius-btn": "3px",
      "--shadow-card": "0 2px 5px rgba(60,45,20,0.25)" },
    dark: { ...base,
      "--bg": "#1C1914", "--panel": "#28241C", "--line": "#4A4232", "--line-strong": "#8A7C60",
      "--text": "#C6BBA2", "--bright": "#EFE6D0", "--dim": "#7E7460", "--label": "#A99A78",
      "--accent": "#D96A50", "--on-accent": "#2A0F06", "--danger": "#D96A50", "--ok": "#7FA060",
      "--font-display": "'Spline Sans Mono', monospace",
      "--radius-card": "3px", "--radius-btn": "3px",
      "--shadow-card": "0 2px 5px rgba(0,0,0,0.4)" },
  },

  clay: {
    name: "Clay", hint: "Soft, puffy, friendly", layout: "stack",
    strings: { pending: "Waiting for you", working: "Being made", recent: "All done",
      directive: "What should we make today?", send: "Let's go", daily: "Fresh ideas" },
    light: { ...base,
      "--bg": "#EEF1FB", "--panel": "#FFFFFF", "--line": "#E3E7F6", "--line-strong": "#C6CDEA",
      "--text": "#4A4F70", "--bright": "#2E3354", "--dim": "#8B91B8", "--label": "#7A81AC",
      "--accent": "#7C6FFF", "--on-accent": "#FFFFFF", "--danger": "#F0637E", "--ok": "#3FBF8F",
      "--radius-card": "22px", "--radius-btn": "16px",
      "--shadow-card": "0 10px 20px rgba(93,107,178,0.18), inset 0 -4px 8px rgba(93,107,178,0.08)",
      "--shadow-btn": "0 6px 12px rgba(124,111,255,0.35), inset 0 -3px 6px rgba(0,0,0,0.12)" },
    dark: { ...base,
      "--bg": "#1B1D2E", "--panel": "#262A42", "--line": "#323756", "--line-strong": "#4A5078",
      "--text": "#B9BEDD", "--bright": "#EDEFFC", "--dim": "#767CA5", "--label": "#8F95C0",
      "--accent": "#8F84FF", "--on-accent": "#14122E", "--danger": "#F0637E", "--ok": "#4FCF9C",
      "--radius-card": "22px", "--radius-btn": "16px",
      "--shadow-card": "0 10px 20px rgba(0,0,0,0.35), inset 0 -4px 8px rgba(0,0,0,0.25)",
      "--shadow-btn": "0 6px 12px rgba(0,0,0,0.4), inset 0 -3px 6px rgba(0,0,0,0.3)" },
  },

  neumorph: {
    name: "Neumorph", hint: "Carved from one surface", layout: "list",
    strings: { pending: "On the desk", working: "In motion", recent: "Recent",
      directive: "Give a directive…", send: "Send", daily: "Daily ideas" },
    light: { ...base,
      "--bg": "#E4E7EE", "--panel": "#E4E7EE", "--line": "#E4E7EE", "--line-strong": "#C9CDD8",
      "--text": "#5A5F70", "--bright": "#3A3F50", "--dim": "#9297A8", "--label": "#7E8398",
      "--accent": "#5B6BD6", "--on-accent": "#FFFFFF", "--danger": "#C05555", "--ok": "#4A9070",
      "--radius-card": "18px", "--radius-btn": "14px",
      "--shadow-card": "7px 7px 14px #C3C7D1, -7px -7px 14px #FFFFFF",
      "--shadow-btn": "5px 5px 10px #C3C7D1, -5px -5px 10px #FFFFFF" },
    dark: { ...base,
      "--bg": "#23262E", "--panel": "#23262E", "--line": "#23262E", "--line-strong": "#3A3E4A",
      "--text": "#A9AEC0", "--bright": "#E4E7F2", "--dim": "#6C7184", "--label": "#8A8FA4",
      "--accent": "#7C8AF0", "--on-accent": "#12141C", "--danger": "#D06868", "--ok": "#5FAF8A",
      "--radius-card": "18px", "--radius-btn": "14px",
      "--shadow-card": "7px 7px 14px #1A1C22, -7px -7px 14px #2C3040",
      "--shadow-btn": "5px 5px 10px #1A1C22, -5px -5px 10px #2C3040" },
  },

  maximal: {
    name: "Maximal", hint: "Chaos, on purpose", layout: "stamps",
    strings: { pending: "LOOK AT THIS!!", working: "cooking rn", recent: "old news",
      directive: "scream an idea into the void…", send: "SEND!!!", daily: "CHAOS TIME" },
    light: { ...base,
      "--bg": "#FF4FA3", "--panel": "#FFFFFF", "--line": "#111111", "--line-strong": "#111111",
      "--text": "#26241F", "--bright": "#111111", "--dim": "#8A4070", "--label": "#007A6A",
      "--accent": "#FFE600", "--on-accent": "#111111", "--danger": "#111111", "--ok": "#00C2A8",
      "--font-display": "'Archivo', sans-serif", "--font-label": "'Archivo', sans-serif",
      "--lbl-spacing": "0.5px",
      "--radius-card": "2px", "--radius-btn": "2px", "--bw": "2.5px",
      "--shadow-card": "6px 6px 0 #00C2A8", "--shadow-btn": "4px 4px 0 #111111" },
    dark: { ...base,
      "--bg": "#1A0A2E", "--panel": "#2A0F45", "--line": "#FF4FA3", "--line-strong": "#FFE600",
      "--text": "#F0D6FF", "--bright": "#FFFFFF", "--dim": "#B080D0", "--label": "#00E6C8",
      "--accent": "#FFE600", "--on-accent": "#111111", "--danger": "#FF4FA3", "--ok": "#00E6C8",
      "--font-display": "'Archivo', sans-serif", "--font-label": "'Archivo', sans-serif",
      "--lbl-spacing": "0.5px",
      "--radius-card": "2px", "--radius-btn": "2px", "--bw": "2.5px",
      "--shadow-card": "6px 6px 0 #00E6C8", "--shadow-btn": "4px 4px 0 #FF4FA3" },
  },

  terminal: {
    name: "Terminal", hint: "Green phosphor, HUD", layout: "term",
    strings: { pending: "INBOX // AWAITING_AUTH", working: "PROC // RUNNING", recent: "LOG // ARCHIVE",
      directive: "$ issue directive…", send: "[EXEC]", daily: "[CRON]" },
    light: { ...base,
      "--bg": "#F2F5F0", "--panel": "#FFFFFF", "--line": "#B8C8B8", "--line-strong": "#5A7A5A",
      "--text": "#2A4A34", "--bright": "#12301C", "--dim": "#7A9A82", "--label": "#3E7A52",
      "--accent": "#1D9E57", "--on-accent": "#F2FFF6", "--danger": "#C04040", "--ok": "#1D9E57",
      "--font-body": "'Spline Sans Mono', monospace", "--font-display": "'Spline Sans Mono', monospace",
      "--radius-card": "4px", "--radius-btn": "4px" },
    dark: { ...base,
      "--bg": "#07090B", "--panel": "#0C1210", "--line": "#183828", "--line-strong": "#3EF08A",
      "--text": "#8ADFAE", "--bright": "#C8FFDF", "--dim": "#4A8A64", "--label": "#3EF08A",
      "--accent": "#3EF08A", "--on-accent": "#04180C", "--danger": "#FF5A5A", "--ok": "#3EF08A",
      "--font-body": "'Spline Sans Mono', monospace", "--font-display": "'Spline Sans Mono', monospace",
      "--radius-card": "4px", "--radius-btn": "4px" },
  },

  bento: {
    name: "Bento", hint: "Everything in tiles", layout: "bento",
    strings: { pending: "Needs you", working: "In flight", recent: "Shipped",
      directive: "Direct the company…", send: "Send", daily: "Daily cycle" },
    light: { ...base,
      "--bg": "#F2F2F4", "--panel": "#FFFFFF", "--line": "#EBEBEE", "--line-strong": "#D2D2D8",
      "--text": "#3F3F46", "--bright": "#18181B", "--dim": "#8E8E96", "--label": "#71717A",
      "--lbl-transform": "none", "--lbl-spacing": "0.2px",
      "--font-label": "'Instrument Sans', sans-serif",
      "--accent": "#FF6B4A", "--on-accent": "#3A1105", "--danger": "#DC2626", "--ok": "#16A34A",
      "--radius-card": "14px", "--radius-btn": "11px" },
    dark: { ...base,
      "--bg": "#101012", "--panel": "#1B1B1F", "--line": "#28282E", "--line-strong": "#3F3F48",
      "--text": "#C4C4CC", "--bright": "#F4F4F6", "--dim": "#7A7A85", "--label": "#9A9AA5",
      "--lbl-transform": "none", "--lbl-spacing": "0.2px",
      "--font-label": "'Instrument Sans', sans-serif",
      "--accent": "#FF7A5C", "--on-accent": "#3A1105", "--danger": "#EF4444", "--ok": "#22C55E",
      "--radius-card": "14px", "--radius-btn": "11px" },
  },

  y2k: {
    name: "Y2K", hint: "Chrome, gloss, 2001", layout: "stack",
    strings: { pending: "★ new 4 u ★", working: "loading…", recent: "yesterdayz",
      directive: "type ur command here!!", send: "GO ►", daily: "~refresh~" },
    light: { ...base,
      "--bg": "#C8DCFF",
      "--bg-image": "linear-gradient(180deg,#B3D4FF 0%,#E8D4FF 100%)",
      "--panel": "#F4F9FF", "--line": "#8FA6D9", "--line-strong": "#5A6FB0",
      "--text": "#2A3A7A", "--bright": "#1B2C6B", "--dim": "#7A89C4", "--label": "#5A6BB0",
      "--accent": "#3FA9F5", "--on-accent": "#062A4A", "--danger": "#E0559A", "--ok": "#3FC98A",
      "--radius-card": "10px", "--radius-btn": "99px",
      "--shadow-card": "0 3px 0 rgba(90,111,176,0.35)",
      "--shadow-btn": "inset 0 2px 0 rgba(255,255,255,0.8), 0 3px 0 rgba(27,123,192,0.5)" },
    dark: { ...base,
      "--bg": "#0E1030",
      "--bg-image": "linear-gradient(180deg,#141650 0%,#33125A 100%)",
      "--panel": "#1D2050", "--line": "#3A3F8A", "--line-strong": "#7C82E0",
      "--text": "#B8BCF0", "--bright": "#EDEEFF", "--dim": "#6E74B8", "--label": "#8F95E8",
      "--accent": "#5CC8FF", "--on-accent": "#062A4A", "--danger": "#FF6EB0", "--ok": "#4FE0A0",
      "--radius-card": "10px", "--radius-btn": "99px",
      "--shadow-card": "0 3px 0 rgba(0,0,0,0.45)",
      "--shadow-btn": "inset 0 2px 0 rgba(255,255,255,0.25), 0 3px 0 rgba(0,0,0,0.5)" },
  },
};

const KEY = "hq_theme";

export function loadTheme() {
  try {
    const t = JSON.parse(localStorage.getItem(KEY));
    if (t && THEMES[t.style]) return t;
  } catch {}
  const prefersDark = window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches;
  return { style: "studio", mode: prefersDark ? "dark" : "light" };
}

export function applyTheme({ style, mode }) {
  const vars = (THEMES[style] || THEMES.studio)[mode === "dark" ? "dark" : "light"];
  const root = document.documentElement;
  Object.entries(vars).forEach(([k, v]) => root.style.setProperty(k, v));
  root.dataset.theme = style;
  root.dataset.mode = mode;
  localStorage.setItem(KEY, JSON.stringify({ style, mode }));
}
