# Generated by Django 6.0.7 on 2026-07-18 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('failed', 'failed')], default='running', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(max_length=120)),
                ('department', models.CharField(max_length=120)),
                ('persona', models.TextField(help_text="Character, expertise, background — the agent's system prompt core")),
                ('mandate', models.CharField(blank=True, default='', max_length=200)),
                ('is_head', models.BooleanField(default=False)),
                ('proactive', models.BooleanField(default=False, help_text='Generates ideas in the daily cycle')),
                ('shape', models.CharField(choices=[('circle', 'circle'), ('diamond', 'diamond'), ('square', 'square'), ('chevron', 'chevron'), ('triad', 'triad')], default='circle', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.agent')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('data_source', 'Data source (read-only JSON endpoint)'), ('web_note', 'Standing knowledge / notes')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True, default='')),
                ('auth_header', models.CharField(blank=True, default='', help_text='e.g. Authorization: Bearer xxx', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='core.agent')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.agent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DelibMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField(default=1)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent')),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.deliberation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='deliberation',
            name='directive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliberations', to='core.directive'),
        ),
        migrations.AddField(
            model_name='directive',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directives', to='core.organization'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='core.organization'),
        ),
        migrations.CreateModel(
            name='Constitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constitution', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('rationale', models.TextField(blank=True, default='', help_text='Provenance: who argued what, and why this won')),
                ('status', models.CharField(choices=[('pending', 'Awaiting CEO decision'), ('revision', 'Sent back for revision'), ('approved', 'Approved — executing'), ('artifact_pending', 'Work submitted for sign-off'), ('done', 'Done'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ceo_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_assigned', to='core.agent')),
                ('deliberation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='core.deliberation')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='core.organization')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals_made', to='core.agent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('html', 'html'), ('markdown', 'markdown'), ('text', 'text')], default='markdown', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10)),
                ('ceo_feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.proposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
