# Generated by Django 6.0.7 on 2026-07-18 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='delivery',
            field=models.TextField(blank=True, default='', help_text='Result of outbound webhook delivery, if any'),
        ),
        migrations.AlterField(
            model_name='capability',
            name='kind',
            field=models.CharField(choices=[('data_source', 'Data source (read-only JSON endpoint)'), ('web_note', 'Standing knowledge / notes'), ('web_research', 'Live web research (agent can search the web)'), ('webhook', 'Outbound action — POST approved deliverables to a URL')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrgMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='core.organization')),
            ],
        ),
    ]
