# Generated by Django 6.0.7 on 2026-07-20 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agent_is_human_agent_user_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField(help_text="e.g. Produce one event flyer for this week's featured event")),
                ('cadence', models.CharField(choices=[('daily', 'Every day'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, help_text='0=Mon … 6=Sun (weekly only)', null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='core.agent')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, default='', max_length=40)),
                ('model', models.CharField(blank=True, default='', max_length=60)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage', to='core.agent')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='core.organization')),
            ],
        ),
    ]
