# Generated by Django 6.0.7 on 2026-07-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_standingorder_usagerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=120)),
                ('proposal_approval', models.CharField(choices=[('ceo', 'CEO'), ('head', 'Human department head'), ('ai_manager', 'AI manager (auto)')], default='ceo', max_length=12)),
                ('artifact_approval', models.CharField(choices=[('ceo', 'CEO'), ('head', 'Human department head')], default='ceo', max_length=12)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='core.organization')),
            ],
            options={
                'unique_together': {('org', 'department')},
            },
        ),
    ]
